# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/william/Documents/codingProj/tinyweb/CTinyWeb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/william/Documents/codingProj/tinyweb/CTinyWeb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/william/Documents/codingProj/tinyweb/CTinyWeb/CMakeFiles /home/william/Documents/codingProj/tinyweb/CTinyWeb//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/william/Documents/codingProj/tinyweb/CTinyWeb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named generate_proto

# Build rule for target.
generate_proto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generate_proto
.PHONY : generate_proto

# fast build rule for target.
generate_proto/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_proto.dir/build.make CMakeFiles/generate_proto.dir/build
.PHONY : generate_proto/fast

#=============================================================================
# Target rules for targets named tinyweb

# Build rule for target.
tinyweb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tinyweb
.PHONY : tinyweb

# fast build rule for target.
tinyweb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/build
.PHONY : tinyweb/fast

#=============================================================================
# Target rules for targets named tinyweb_tests

# Build rule for target.
tinyweb_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tinyweb_tests
.PHONY : tinyweb_tests

# fast build rule for target.
tinyweb_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/build
.PHONY : tinyweb_tests/fast

#=============================================================================
# Target rules for targets named init_tool

# Build rule for target.
init_tool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 init_tool
.PHONY : init_tool

# fast build rule for target.
init_tool/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/build
.PHONY : init_tool/fast

generated/api.pb-c.o: generated/api.pb-c.c.o
.PHONY : generated/api.pb-c.o

# target to build an object file
generated/api.pb-c.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/generated/api.pb-c.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/generated/api.pb-c.c.o
.PHONY : generated/api.pb-c.c.o

generated/api.pb-c.i: generated/api.pb-c.c.i
.PHONY : generated/api.pb-c.i

# target to preprocess a source file
generated/api.pb-c.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/generated/api.pb-c.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/generated/api.pb-c.c.i
.PHONY : generated/api.pb-c.c.i

generated/api.pb-c.s: generated/api.pb-c.c.s
.PHONY : generated/api.pb-c.s

# target to generate assembly for a file
generated/api.pb-c.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/generated/api.pb-c.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/generated/api.pb-c.c.s
.PHONY : generated/api.pb-c.c.s

generated/content.pb-c.o: generated/content.pb-c.c.o
.PHONY : generated/content.pb-c.o

# target to build an object file
generated/content.pb-c.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/generated/content.pb-c.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/generated/content.pb-c.c.o
.PHONY : generated/content.pb-c.c.o

generated/content.pb-c.i: generated/content.pb-c.c.i
.PHONY : generated/content.pb-c.i

# target to preprocess a source file
generated/content.pb-c.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/generated/content.pb-c.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/generated/content.pb-c.c.i
.PHONY : generated/content.pb-c.c.i

generated/content.pb-c.s: generated/content.pb-c.c.s
.PHONY : generated/content.pb-c.s

# target to generate assembly for a file
generated/content.pb-c.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/generated/content.pb-c.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/generated/content.pb-c.c.s
.PHONY : generated/content.pb-c.c.s

generated/envelope.pb-c.o: generated/envelope.pb-c.c.o
.PHONY : generated/envelope.pb-c.o

# target to build an object file
generated/envelope.pb-c.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/generated/envelope.pb-c.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/generated/envelope.pb-c.c.o
.PHONY : generated/envelope.pb-c.c.o

generated/envelope.pb-c.i: generated/envelope.pb-c.c.i
.PHONY : generated/envelope.pb-c.i

# target to preprocess a source file
generated/envelope.pb-c.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/generated/envelope.pb-c.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/generated/envelope.pb-c.c.i
.PHONY : generated/envelope.pb-c.c.i

generated/envelope.pb-c.s: generated/envelope.pb-c.c.s
.PHONY : generated/envelope.pb-c.s

# target to generate assembly for a file
generated/envelope.pb-c.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/generated/envelope.pb-c.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/generated/envelope.pb-c.c.s
.PHONY : generated/envelope.pb-c.c.s

src/external/mongoose/mongoose.o: src/external/mongoose/mongoose.c.o
.PHONY : src/external/mongoose/mongoose.o

# target to build an object file
src/external/mongoose/mongoose.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/external/mongoose/mongoose.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/external/mongoose/mongoose.c.o
.PHONY : src/external/mongoose/mongoose.c.o

src/external/mongoose/mongoose.i: src/external/mongoose/mongoose.c.i
.PHONY : src/external/mongoose/mongoose.i

# target to preprocess a source file
src/external/mongoose/mongoose.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/external/mongoose/mongoose.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/external/mongoose/mongoose.c.i
.PHONY : src/external/mongoose/mongoose.c.i

src/external/mongoose/mongoose.s: src/external/mongoose/mongoose.c.s
.PHONY : src/external/mongoose/mongoose.s

# target to generate assembly for a file
src/external/mongoose/mongoose.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/external/mongoose/mongoose.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/external/mongoose/mongoose.c.s
.PHONY : src/external/mongoose/mongoose.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/main.c.s
.PHONY : src/main.c.s

src/packages/comm/envelope_dispatcher.o: src/packages/comm/envelope_dispatcher.c.o
.PHONY : src/packages/comm/envelope_dispatcher.o

# target to build an object file
src/packages/comm/envelope_dispatcher.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/comm/envelope_dispatcher.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/comm/envelope_dispatcher.c.o
.PHONY : src/packages/comm/envelope_dispatcher.c.o

src/packages/comm/envelope_dispatcher.i: src/packages/comm/envelope_dispatcher.c.i
.PHONY : src/packages/comm/envelope_dispatcher.i

# target to preprocess a source file
src/packages/comm/envelope_dispatcher.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/comm/envelope_dispatcher.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/comm/envelope_dispatcher.c.i
.PHONY : src/packages/comm/envelope_dispatcher.c.i

src/packages/comm/envelope_dispatcher.s: src/packages/comm/envelope_dispatcher.c.s
.PHONY : src/packages/comm/envelope_dispatcher.s

# target to generate assembly for a file
src/packages/comm/envelope_dispatcher.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/comm/envelope_dispatcher.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/comm/envelope_dispatcher.c.s
.PHONY : src/packages/comm/envelope_dispatcher.c.s

src/packages/comm/gossip/gossip.o: src/packages/comm/gossip/gossip.c.o
.PHONY : src/packages/comm/gossip/gossip.o

# target to build an object file
src/packages/comm/gossip/gossip.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/comm/gossip/gossip.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/comm/gossip/gossip.c.o
.PHONY : src/packages/comm/gossip/gossip.c.o

src/packages/comm/gossip/gossip.i: src/packages/comm/gossip/gossip.c.i
.PHONY : src/packages/comm/gossip/gossip.i

# target to preprocess a source file
src/packages/comm/gossip/gossip.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/comm/gossip/gossip.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/comm/gossip/gossip.c.i
.PHONY : src/packages/comm/gossip/gossip.c.i

src/packages/comm/gossip/gossip.s: src/packages/comm/gossip/gossip.c.s
.PHONY : src/packages/comm/gossip/gossip.s

# target to generate assembly for a file
src/packages/comm/gossip/gossip.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/comm/gossip/gossip.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/comm/gossip/gossip.c.s
.PHONY : src/packages/comm/gossip/gossip.c.s

src/packages/comm/gossipApi.o: src/packages/comm/gossipApi.c.o
.PHONY : src/packages/comm/gossipApi.o

# target to build an object file
src/packages/comm/gossipApi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/comm/gossipApi.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/comm/gossipApi.c.o
.PHONY : src/packages/comm/gossipApi.c.o

src/packages/comm/gossipApi.i: src/packages/comm/gossipApi.c.i
.PHONY : src/packages/comm/gossipApi.i

# target to preprocess a source file
src/packages/comm/gossipApi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/comm/gossipApi.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/comm/gossipApi.c.i
.PHONY : src/packages/comm/gossipApi.c.i

src/packages/comm/gossipApi.s: src/packages/comm/gossipApi.c.s
.PHONY : src/packages/comm/gossipApi.s

# target to generate assembly for a file
src/packages/comm/gossipApi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/comm/gossipApi.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/comm/gossipApi.c.s
.PHONY : src/packages/comm/gossipApi.c.s

src/packages/comm/httpClient.o: src/packages/comm/httpClient.c.o
.PHONY : src/packages/comm/httpClient.o

# target to build an object file
src/packages/comm/httpClient.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/comm/httpClient.c.o
.PHONY : src/packages/comm/httpClient.c.o

src/packages/comm/httpClient.i: src/packages/comm/httpClient.c.i
.PHONY : src/packages/comm/httpClient.i

# target to preprocess a source file
src/packages/comm/httpClient.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/comm/httpClient.c.i
.PHONY : src/packages/comm/httpClient.c.i

src/packages/comm/httpClient.s: src/packages/comm/httpClient.c.s
.PHONY : src/packages/comm/httpClient.s

# target to generate assembly for a file
src/packages/comm/httpClient.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/comm/httpClient.c.s
.PHONY : src/packages/comm/httpClient.c.s

src/packages/encryption/encryption.o: src/packages/encryption/encryption.c.o
.PHONY : src/packages/encryption/encryption.o

# target to build an object file
src/packages/encryption/encryption.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/encryption/encryption.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/encryption/encryption.c.o
.PHONY : src/packages/encryption/encryption.c.o

src/packages/encryption/encryption.i: src/packages/encryption/encryption.c.i
.PHONY : src/packages/encryption/encryption.i

# target to preprocess a source file
src/packages/encryption/encryption.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/encryption/encryption.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/encryption/encryption.c.i
.PHONY : src/packages/encryption/encryption.c.i

src/packages/encryption/encryption.s: src/packages/encryption/encryption.c.s
.PHONY : src/packages/encryption/encryption.s

# target to generate assembly for a file
src/packages/encryption/encryption.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/encryption/encryption.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/encryption/encryption.c.s
.PHONY : src/packages/encryption/encryption.c.s

src/packages/initialization/init.o: src/packages/initialization/init.c.o
.PHONY : src/packages/initialization/init.o

# target to build an object file
src/packages/initialization/init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/initialization/init.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/initialization/init.c.o
.PHONY : src/packages/initialization/init.c.o

src/packages/initialization/init.i: src/packages/initialization/init.c.i
.PHONY : src/packages/initialization/init.i

# target to preprocess a source file
src/packages/initialization/init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/initialization/init.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/initialization/init.c.i
.PHONY : src/packages/initialization/init.c.i

src/packages/initialization/init.s: src/packages/initialization/init.c.s
.PHONY : src/packages/initialization/init.s

# target to generate assembly for a file
src/packages/initialization/init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/initialization/init.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/initialization/init.c.s
.PHONY : src/packages/initialization/init.c.s

src/packages/initialization/init_tool.o: src/packages/initialization/init_tool.c.o
.PHONY : src/packages/initialization/init_tool.o

# target to build an object file
src/packages/initialization/init_tool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/initialization/init_tool.c.o
.PHONY : src/packages/initialization/init_tool.c.o

src/packages/initialization/init_tool.i: src/packages/initialization/init_tool.c.i
.PHONY : src/packages/initialization/init_tool.i

# target to preprocess a source file
src/packages/initialization/init_tool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/initialization/init_tool.c.i
.PHONY : src/packages/initialization/init_tool.c.i

src/packages/initialization/init_tool.s: src/packages/initialization/init_tool.c.s
.PHONY : src/packages/initialization/init_tool.s

# target to generate assembly for a file
src/packages/initialization/init_tool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/initialization/init_tool.c.s
.PHONY : src/packages/initialization/init_tool.c.s

src/packages/keystore/keystore.o: src/packages/keystore/keystore.c.o
.PHONY : src/packages/keystore/keystore.o

# target to build an object file
src/packages/keystore/keystore.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/keystore/keystore.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/keystore/keystore.c.o
.PHONY : src/packages/keystore/keystore.c.o

src/packages/keystore/keystore.i: src/packages/keystore/keystore.c.i
.PHONY : src/packages/keystore/keystore.i

# target to preprocess a source file
src/packages/keystore/keystore.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/keystore/keystore.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/keystore/keystore.c.i
.PHONY : src/packages/keystore/keystore.c.i

src/packages/keystore/keystore.s: src/packages/keystore/keystore.c.s
.PHONY : src/packages/keystore/keystore.s

# target to generate assembly for a file
src/packages/keystore/keystore.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/keystore/keystore.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/keystore/keystore.c.s
.PHONY : src/packages/keystore/keystore.c.s

src/packages/signing/signing.o: src/packages/signing/signing.c.o
.PHONY : src/packages/signing/signing.o

# target to build an object file
src/packages/signing/signing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/signing/signing.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/signing/signing.c.o
.PHONY : src/packages/signing/signing.c.o

src/packages/signing/signing.i: src/packages/signing/signing.c.i
.PHONY : src/packages/signing/signing.i

# target to preprocess a source file
src/packages/signing/signing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/signing/signing.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/signing/signing.c.i
.PHONY : src/packages/signing/signing.c.i

src/packages/signing/signing.s: src/packages/signing/signing.c.s
.PHONY : src/packages/signing/signing.s

# target to generate assembly for a file
src/packages/signing/signing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/signing/signing.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/signing/signing.c.s
.PHONY : src/packages/signing/signing.c.s

src/packages/sql/database_gossip.o: src/packages/sql/database_gossip.c.o
.PHONY : src/packages/sql/database_gossip.o

# target to build an object file
src/packages/sql/database_gossip.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/sql/database_gossip.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/sql/database_gossip.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/sql/database_gossip.c.o
.PHONY : src/packages/sql/database_gossip.c.o

src/packages/sql/database_gossip.i: src/packages/sql/database_gossip.c.i
.PHONY : src/packages/sql/database_gossip.i

# target to preprocess a source file
src/packages/sql/database_gossip.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/sql/database_gossip.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/sql/database_gossip.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/sql/database_gossip.c.i
.PHONY : src/packages/sql/database_gossip.c.i

src/packages/sql/database_gossip.s: src/packages/sql/database_gossip.c.s
.PHONY : src/packages/sql/database_gossip.s

# target to generate assembly for a file
src/packages/sql/database_gossip.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/sql/database_gossip.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/sql/database_gossip.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/sql/database_gossip.c.s
.PHONY : src/packages/sql/database_gossip.c.s

src/packages/sql/gossip_peers.o: src/packages/sql/gossip_peers.c.o
.PHONY : src/packages/sql/gossip_peers.o

# target to build an object file
src/packages/sql/gossip_peers.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/sql/gossip_peers.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/sql/gossip_peers.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/sql/gossip_peers.c.o
.PHONY : src/packages/sql/gossip_peers.c.o

src/packages/sql/gossip_peers.i: src/packages/sql/gossip_peers.c.i
.PHONY : src/packages/sql/gossip_peers.i

# target to preprocess a source file
src/packages/sql/gossip_peers.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/sql/gossip_peers.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/sql/gossip_peers.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/sql/gossip_peers.c.i
.PHONY : src/packages/sql/gossip_peers.c.i

src/packages/sql/gossip_peers.s: src/packages/sql/gossip_peers.c.s
.PHONY : src/packages/sql/gossip_peers.s

# target to generate assembly for a file
src/packages/sql/gossip_peers.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/sql/gossip_peers.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/sql/gossip_peers.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/sql/gossip_peers.c.s
.PHONY : src/packages/sql/gossip_peers.c.s

src/packages/sql/gossip_store.o: src/packages/sql/gossip_store.c.o
.PHONY : src/packages/sql/gossip_store.o

# target to build an object file
src/packages/sql/gossip_store.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/sql/gossip_store.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/sql/gossip_store.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/sql/gossip_store.c.o
.PHONY : src/packages/sql/gossip_store.c.o

src/packages/sql/gossip_store.i: src/packages/sql/gossip_store.c.i
.PHONY : src/packages/sql/gossip_store.i

# target to preprocess a source file
src/packages/sql/gossip_store.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/sql/gossip_store.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/sql/gossip_store.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/sql/gossip_store.c.i
.PHONY : src/packages/sql/gossip_store.c.i

src/packages/sql/gossip_store.s: src/packages/sql/gossip_store.c.s
.PHONY : src/packages/sql/gossip_store.s

# target to generate assembly for a file
src/packages/sql/gossip_store.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/sql/gossip_store.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/sql/gossip_store.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/sql/gossip_store.c.s
.PHONY : src/packages/sql/gossip_store.c.s

src/packages/sql/permissions.o: src/packages/sql/permissions.c.o
.PHONY : src/packages/sql/permissions.o

# target to build an object file
src/packages/sql/permissions.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/sql/permissions.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/sql/permissions.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/sql/permissions.c.o
.PHONY : src/packages/sql/permissions.c.o

src/packages/sql/permissions.i: src/packages/sql/permissions.c.i
.PHONY : src/packages/sql/permissions.i

# target to preprocess a source file
src/packages/sql/permissions.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/sql/permissions.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/sql/permissions.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/sql/permissions.c.i
.PHONY : src/packages/sql/permissions.c.i

src/packages/sql/permissions.s: src/packages/sql/permissions.c.s
.PHONY : src/packages/sql/permissions.s

# target to generate assembly for a file
src/packages/sql/permissions.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/sql/permissions.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/sql/permissions.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/sql/permissions.c.s
.PHONY : src/packages/sql/permissions.c.s

src/packages/sql/schema.o: src/packages/sql/schema.c.o
.PHONY : src/packages/sql/schema.o

# target to build an object file
src/packages/sql/schema.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/sql/schema.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/sql/schema.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/sql/schema.c.o
.PHONY : src/packages/sql/schema.c.o

src/packages/sql/schema.i: src/packages/sql/schema.c.i
.PHONY : src/packages/sql/schema.i

# target to preprocess a source file
src/packages/sql/schema.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/sql/schema.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/sql/schema.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/sql/schema.c.i
.PHONY : src/packages/sql/schema.c.i

src/packages/sql/schema.s: src/packages/sql/schema.c.s
.PHONY : src/packages/sql/schema.s

# target to generate assembly for a file
src/packages/sql/schema.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/sql/schema.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/sql/schema.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/sql/schema.c.s
.PHONY : src/packages/sql/schema.c.s

src/packages/transactions/envelope.o: src/packages/transactions/envelope.c.o
.PHONY : src/packages/transactions/envelope.o

# target to build an object file
src/packages/transactions/envelope.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/transactions/envelope.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/transactions/envelope.c.o
.PHONY : src/packages/transactions/envelope.c.o

src/packages/transactions/envelope.i: src/packages/transactions/envelope.c.i
.PHONY : src/packages/transactions/envelope.i

# target to preprocess a source file
src/packages/transactions/envelope.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/transactions/envelope.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/transactions/envelope.c.i
.PHONY : src/packages/transactions/envelope.c.i

src/packages/transactions/envelope.s: src/packages/transactions/envelope.c.s
.PHONY : src/packages/transactions/envelope.s

# target to generate assembly for a file
src/packages/transactions/envelope.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/transactions/envelope.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/transactions/envelope.c.s
.PHONY : src/packages/transactions/envelope.c.s

src/packages/utils/byteorder.o: src/packages/utils/byteorder.c.o
.PHONY : src/packages/utils/byteorder.o

# target to build an object file
src/packages/utils/byteorder.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/utils/byteorder.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/utils/byteorder.c.o
.PHONY : src/packages/utils/byteorder.c.o

src/packages/utils/byteorder.i: src/packages/utils/byteorder.c.i
.PHONY : src/packages/utils/byteorder.i

# target to preprocess a source file
src/packages/utils/byteorder.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/utils/byteorder.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/utils/byteorder.c.i
.PHONY : src/packages/utils/byteorder.c.i

src/packages/utils/byteorder.s: src/packages/utils/byteorder.c.s
.PHONY : src/packages/utils/byteorder.s

# target to generate assembly for a file
src/packages/utils/byteorder.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/utils/byteorder.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/utils/byteorder.c.s
.PHONY : src/packages/utils/byteorder.c.s

src/packages/utils/logger.o: src/packages/utils/logger.c.o
.PHONY : src/packages/utils/logger.o

# target to build an object file
src/packages/utils/logger.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/utils/logger.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/utils/logger.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/utils/logger.c.o
.PHONY : src/packages/utils/logger.c.o

src/packages/utils/logger.i: src/packages/utils/logger.c.i
.PHONY : src/packages/utils/logger.i

# target to preprocess a source file
src/packages/utils/logger.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/utils/logger.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/utils/logger.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/utils/logger.c.i
.PHONY : src/packages/utils/logger.c.i

src/packages/utils/logger.s: src/packages/utils/logger.c.s
.PHONY : src/packages/utils/logger.s

# target to generate assembly for a file
src/packages/utils/logger.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/utils/logger.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/utils/logger.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/packages/utils/logger.c.s
.PHONY : src/packages/utils/logger.c.s

src/packages/utils/print.o: src/packages/utils/print.c.o
.PHONY : src/packages/utils/print.o

# target to build an object file
src/packages/utils/print.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/utils/print.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/utils/print.c.o
.PHONY : src/packages/utils/print.c.o

src/packages/utils/print.i: src/packages/utils/print.c.i
.PHONY : src/packages/utils/print.i

# target to preprocess a source file
src/packages/utils/print.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/utils/print.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/utils/print.c.i
.PHONY : src/packages/utils/print.c.i

src/packages/utils/print.s: src/packages/utils/print.c.s
.PHONY : src/packages/utils/print.s

# target to generate assembly for a file
src/packages/utils/print.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/utils/print.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/utils/print.c.s
.PHONY : src/packages/utils/print.c.s

src/packages/utils/statePaths.o: src/packages/utils/statePaths.c.o
.PHONY : src/packages/utils/statePaths.o

# target to build an object file
src/packages/utils/statePaths.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/utils/statePaths.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/utils/statePaths.c.o
.PHONY : src/packages/utils/statePaths.c.o

src/packages/utils/statePaths.i: src/packages/utils/statePaths.c.i
.PHONY : src/packages/utils/statePaths.i

# target to preprocess a source file
src/packages/utils/statePaths.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/utils/statePaths.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/utils/statePaths.c.i
.PHONY : src/packages/utils/statePaths.c.i

src/packages/utils/statePaths.s: src/packages/utils/statePaths.c.s
.PHONY : src/packages/utils/statePaths.s

# target to generate assembly for a file
src/packages/utils/statePaths.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/utils/statePaths.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/utils/statePaths.c.s
.PHONY : src/packages/utils/statePaths.c.s

src/packages/validation/gossip_validation.o: src/packages/validation/gossip_validation.c.o
.PHONY : src/packages/validation/gossip_validation.o

# target to build an object file
src/packages/validation/gossip_validation.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/validation/gossip_validation.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/validation/gossip_validation.c.o
.PHONY : src/packages/validation/gossip_validation.c.o

src/packages/validation/gossip_validation.i: src/packages/validation/gossip_validation.c.i
.PHONY : src/packages/validation/gossip_validation.i

# target to preprocess a source file
src/packages/validation/gossip_validation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/validation/gossip_validation.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/validation/gossip_validation.c.i
.PHONY : src/packages/validation/gossip_validation.c.i

src/packages/validation/gossip_validation.s: src/packages/validation/gossip_validation.c.s
.PHONY : src/packages/validation/gossip_validation.s

# target to generate assembly for a file
src/packages/validation/gossip_validation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/packages/validation/gossip_validation.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/packages/validation/gossip_validation.c.s
.PHONY : src/packages/validation/gossip_validation.c.s

src/structs/permission/permission.o: src/structs/permission/permission.c.o
.PHONY : src/structs/permission/permission.o

# target to build an object file
src/structs/permission/permission.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/structs/permission/permission.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/structs/permission/permission.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/structs/permission/permission.c.o
.PHONY : src/structs/permission/permission.c.o

src/structs/permission/permission.i: src/structs/permission/permission.c.i
.PHONY : src/structs/permission/permission.i

# target to preprocess a source file
src/structs/permission/permission.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/structs/permission/permission.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/structs/permission/permission.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/structs/permission/permission.c.i
.PHONY : src/structs/permission/permission.c.i

src/structs/permission/permission.s: src/structs/permission/permission.c.s
.PHONY : src/structs/permission/permission.s

# target to generate assembly for a file
src/structs/permission/permission.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/structs/permission/permission.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/structs/permission/permission.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/init_tool.dir/build.make CMakeFiles/init_tool.dir/src/structs/permission/permission.c.s
.PHONY : src/structs/permission/permission.c.s

src/tests/api_protobuf_test.o: src/tests/api_protobuf_test.c.o
.PHONY : src/tests/api_protobuf_test.o

# target to build an object file
src/tests/api_protobuf_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/api_protobuf_test.c.o
.PHONY : src/tests/api_protobuf_test.c.o

src/tests/api_protobuf_test.i: src/tests/api_protobuf_test.c.i
.PHONY : src/tests/api_protobuf_test.i

# target to preprocess a source file
src/tests/api_protobuf_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/api_protobuf_test.c.i
.PHONY : src/tests/api_protobuf_test.c.i

src/tests/api_protobuf_test.s: src/tests/api_protobuf_test.c.s
.PHONY : src/tests/api_protobuf_test.s

# target to generate assembly for a file
src/tests/api_protobuf_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/api_protobuf_test.c.s
.PHONY : src/tests/api_protobuf_test.c.s

src/tests/encryption_test.o: src/tests/encryption_test.c.o
.PHONY : src/tests/encryption_test.o

# target to build an object file
src/tests/encryption_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/encryption_test.c.o
.PHONY : src/tests/encryption_test.c.o

src/tests/encryption_test.i: src/tests/encryption_test.c.i
.PHONY : src/tests/encryption_test.i

# target to preprocess a source file
src/tests/encryption_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/encryption_test.c.i
.PHONY : src/tests/encryption_test.c.i

src/tests/encryption_test.s: src/tests/encryption_test.c.s
.PHONY : src/tests/encryption_test.s

# target to generate assembly for a file
src/tests/encryption_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/encryption_test.c.s
.PHONY : src/tests/encryption_test.c.s

src/tests/envelope_dispatcher_test.o: src/tests/envelope_dispatcher_test.c.o
.PHONY : src/tests/envelope_dispatcher_test.o

# target to build an object file
src/tests/envelope_dispatcher_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/envelope_dispatcher_test.c.o
.PHONY : src/tests/envelope_dispatcher_test.c.o

src/tests/envelope_dispatcher_test.i: src/tests/envelope_dispatcher_test.c.i
.PHONY : src/tests/envelope_dispatcher_test.i

# target to preprocess a source file
src/tests/envelope_dispatcher_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/envelope_dispatcher_test.c.i
.PHONY : src/tests/envelope_dispatcher_test.c.i

src/tests/envelope_dispatcher_test.s: src/tests/envelope_dispatcher_test.c.s
.PHONY : src/tests/envelope_dispatcher_test.s

# target to generate assembly for a file
src/tests/envelope_dispatcher_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/envelope_dispatcher_test.c.s
.PHONY : src/tests/envelope_dispatcher_test.c.s

src/tests/envelope_test.o: src/tests/envelope_test.c.o
.PHONY : src/tests/envelope_test.o

# target to build an object file
src/tests/envelope_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/envelope_test.c.o
.PHONY : src/tests/envelope_test.c.o

src/tests/envelope_test.i: src/tests/envelope_test.c.i
.PHONY : src/tests/envelope_test.i

# target to preprocess a source file
src/tests/envelope_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/envelope_test.c.i
.PHONY : src/tests/envelope_test.c.i

src/tests/envelope_test.s: src/tests/envelope_test.c.s
.PHONY : src/tests/envelope_test.s

# target to generate assembly for a file
src/tests/envelope_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/envelope_test.c.s
.PHONY : src/tests/envelope_test.c.s

src/tests/gossip_store_test.o: src/tests/gossip_store_test.c.o
.PHONY : src/tests/gossip_store_test.o

# target to build an object file
src/tests/gossip_store_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/gossip_store_test.c.o
.PHONY : src/tests/gossip_store_test.c.o

src/tests/gossip_store_test.i: src/tests/gossip_store_test.c.i
.PHONY : src/tests/gossip_store_test.i

# target to preprocess a source file
src/tests/gossip_store_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/gossip_store_test.c.i
.PHONY : src/tests/gossip_store_test.c.i

src/tests/gossip_store_test.s: src/tests/gossip_store_test.c.s
.PHONY : src/tests/gossip_store_test.s

# target to generate assembly for a file
src/tests/gossip_store_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/gossip_store_test.c.s
.PHONY : src/tests/gossip_store_test.c.s

src/tests/gossip_validation_test.o: src/tests/gossip_validation_test.c.o
.PHONY : src/tests/gossip_validation_test.o

# target to build an object file
src/tests/gossip_validation_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/gossip_validation_test.c.o
.PHONY : src/tests/gossip_validation_test.c.o

src/tests/gossip_validation_test.i: src/tests/gossip_validation_test.c.i
.PHONY : src/tests/gossip_validation_test.i

# target to preprocess a source file
src/tests/gossip_validation_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/gossip_validation_test.c.i
.PHONY : src/tests/gossip_validation_test.c.i

src/tests/gossip_validation_test.s: src/tests/gossip_validation_test.c.s
.PHONY : src/tests/gossip_validation_test.s

# target to generate assembly for a file
src/tests/gossip_validation_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/gossip_validation_test.c.s
.PHONY : src/tests/gossip_validation_test.c.s

src/tests/httpclient_test.o: src/tests/httpclient_test.c.o
.PHONY : src/tests/httpclient_test.o

# target to build an object file
src/tests/httpclient_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/httpclient_test.c.o
.PHONY : src/tests/httpclient_test.c.o

src/tests/httpclient_test.i: src/tests/httpclient_test.c.i
.PHONY : src/tests/httpclient_test.i

# target to preprocess a source file
src/tests/httpclient_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/httpclient_test.c.i
.PHONY : src/tests/httpclient_test.c.i

src/tests/httpclient_test.s: src/tests/httpclient_test.c.s
.PHONY : src/tests/httpclient_test.s

# target to generate assembly for a file
src/tests/httpclient_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/httpclient_test.c.s
.PHONY : src/tests/httpclient_test.c.s

src/tests/mongoose_test.o: src/tests/mongoose_test.c.o
.PHONY : src/tests/mongoose_test.o

# target to build an object file
src/tests/mongoose_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/mongoose_test.c.o
.PHONY : src/tests/mongoose_test.c.o

src/tests/mongoose_test.i: src/tests/mongoose_test.c.i
.PHONY : src/tests/mongoose_test.i

# target to preprocess a source file
src/tests/mongoose_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/mongoose_test.c.i
.PHONY : src/tests/mongoose_test.c.i

src/tests/mongoose_test.s: src/tests/mongoose_test.c.s
.PHONY : src/tests/mongoose_test.s

# target to generate assembly for a file
src/tests/mongoose_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/mongoose_test.c.s
.PHONY : src/tests/mongoose_test.c.s

src/tests/permissions_test.o: src/tests/permissions_test.c.o
.PHONY : src/tests/permissions_test.o

# target to build an object file
src/tests/permissions_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/permissions_test.c.o
.PHONY : src/tests/permissions_test.c.o

src/tests/permissions_test.i: src/tests/permissions_test.c.i
.PHONY : src/tests/permissions_test.i

# target to preprocess a source file
src/tests/permissions_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/permissions_test.c.i
.PHONY : src/tests/permissions_test.c.i

src/tests/permissions_test.s: src/tests/permissions_test.c.s
.PHONY : src/tests/permissions_test.s

# target to generate assembly for a file
src/tests/permissions_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/permissions_test.c.s
.PHONY : src/tests/permissions_test.c.s

src/tests/schema_test.o: src/tests/schema_test.c.o
.PHONY : src/tests/schema_test.o

# target to build an object file
src/tests/schema_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/schema_test.c.o
.PHONY : src/tests/schema_test.c.o

src/tests/schema_test.i: src/tests/schema_test.c.i
.PHONY : src/tests/schema_test.i

# target to preprocess a source file
src/tests/schema_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/schema_test.c.i
.PHONY : src/tests/schema_test.c.i

src/tests/schema_test.s: src/tests/schema_test.c.s
.PHONY : src/tests/schema_test.s

# target to generate assembly for a file
src/tests/schema_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/schema_test.c.s
.PHONY : src/tests/schema_test.c.s

src/tests/signing_test.o: src/tests/signing_test.c.o
.PHONY : src/tests/signing_test.o

# target to build an object file
src/tests/signing_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/signing_test.c.o
.PHONY : src/tests/signing_test.c.o

src/tests/signing_test.i: src/tests/signing_test.c.i
.PHONY : src/tests/signing_test.i

# target to preprocess a source file
src/tests/signing_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/signing_test.c.i
.PHONY : src/tests/signing_test.c.i

src/tests/signing_test.s: src/tests/signing_test.c.s
.PHONY : src/tests/signing_test.s

# target to generate assembly for a file
src/tests/signing_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/signing_test.c.s
.PHONY : src/tests/signing_test.c.s

src/tests/test_init.o: src/tests/test_init.c.o
.PHONY : src/tests/test_init.o

# target to build an object file
src/tests/test_init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/test_init.c.o
.PHONY : src/tests/test_init.c.o

src/tests/test_init.i: src/tests/test_init.c.i
.PHONY : src/tests/test_init.i

# target to preprocess a source file
src/tests/test_init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/test_init.c.i
.PHONY : src/tests/test_init.c.i

src/tests/test_init.s: src/tests/test_init.c.s
.PHONY : src/tests/test_init.s

# target to generate assembly for a file
src/tests/test_init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/test_init.c.s
.PHONY : src/tests/test_init.c.s

src/tests/test_runner.o: src/tests/test_runner.c.o
.PHONY : src/tests/test_runner.o

# target to build an object file
src/tests/test_runner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/test_runner.c.o
.PHONY : src/tests/test_runner.c.o

src/tests/test_runner.i: src/tests/test_runner.c.i
.PHONY : src/tests/test_runner.i

# target to preprocess a source file
src/tests/test_runner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/test_runner.c.i
.PHONY : src/tests/test_runner.c.i

src/tests/test_runner.s: src/tests/test_runner.c.s
.PHONY : src/tests/test_runner.s

# target to generate assembly for a file
src/tests/test_runner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyweb_tests.dir/build.make CMakeFiles/tinyweb_tests.dir/src/tests/test_runner.c.s
.PHONY : src/tests/test_runner.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... generate_proto"
	@echo "... init_tool"
	@echo "... tinyweb"
	@echo "... tinyweb_tests"
	@echo "... generated/api.pb-c.o"
	@echo "... generated/api.pb-c.i"
	@echo "... generated/api.pb-c.s"
	@echo "... generated/content.pb-c.o"
	@echo "... generated/content.pb-c.i"
	@echo "... generated/content.pb-c.s"
	@echo "... generated/envelope.pb-c.o"
	@echo "... generated/envelope.pb-c.i"
	@echo "... generated/envelope.pb-c.s"
	@echo "... src/external/mongoose/mongoose.o"
	@echo "... src/external/mongoose/mongoose.i"
	@echo "... src/external/mongoose/mongoose.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/packages/comm/envelope_dispatcher.o"
	@echo "... src/packages/comm/envelope_dispatcher.i"
	@echo "... src/packages/comm/envelope_dispatcher.s"
	@echo "... src/packages/comm/gossip/gossip.o"
	@echo "... src/packages/comm/gossip/gossip.i"
	@echo "... src/packages/comm/gossip/gossip.s"
	@echo "... src/packages/comm/gossipApi.o"
	@echo "... src/packages/comm/gossipApi.i"
	@echo "... src/packages/comm/gossipApi.s"
	@echo "... src/packages/comm/httpClient.o"
	@echo "... src/packages/comm/httpClient.i"
	@echo "... src/packages/comm/httpClient.s"
	@echo "... src/packages/encryption/encryption.o"
	@echo "... src/packages/encryption/encryption.i"
	@echo "... src/packages/encryption/encryption.s"
	@echo "... src/packages/initialization/init.o"
	@echo "... src/packages/initialization/init.i"
	@echo "... src/packages/initialization/init.s"
	@echo "... src/packages/initialization/init_tool.o"
	@echo "... src/packages/initialization/init_tool.i"
	@echo "... src/packages/initialization/init_tool.s"
	@echo "... src/packages/keystore/keystore.o"
	@echo "... src/packages/keystore/keystore.i"
	@echo "... src/packages/keystore/keystore.s"
	@echo "... src/packages/signing/signing.o"
	@echo "... src/packages/signing/signing.i"
	@echo "... src/packages/signing/signing.s"
	@echo "... src/packages/sql/database_gossip.o"
	@echo "... src/packages/sql/database_gossip.i"
	@echo "... src/packages/sql/database_gossip.s"
	@echo "... src/packages/sql/gossip_peers.o"
	@echo "... src/packages/sql/gossip_peers.i"
	@echo "... src/packages/sql/gossip_peers.s"
	@echo "... src/packages/sql/gossip_store.o"
	@echo "... src/packages/sql/gossip_store.i"
	@echo "... src/packages/sql/gossip_store.s"
	@echo "... src/packages/sql/permissions.o"
	@echo "... src/packages/sql/permissions.i"
	@echo "... src/packages/sql/permissions.s"
	@echo "... src/packages/sql/schema.o"
	@echo "... src/packages/sql/schema.i"
	@echo "... src/packages/sql/schema.s"
	@echo "... src/packages/transactions/envelope.o"
	@echo "... src/packages/transactions/envelope.i"
	@echo "... src/packages/transactions/envelope.s"
	@echo "... src/packages/utils/byteorder.o"
	@echo "... src/packages/utils/byteorder.i"
	@echo "... src/packages/utils/byteorder.s"
	@echo "... src/packages/utils/logger.o"
	@echo "... src/packages/utils/logger.i"
	@echo "... src/packages/utils/logger.s"
	@echo "... src/packages/utils/print.o"
	@echo "... src/packages/utils/print.i"
	@echo "... src/packages/utils/print.s"
	@echo "... src/packages/utils/statePaths.o"
	@echo "... src/packages/utils/statePaths.i"
	@echo "... src/packages/utils/statePaths.s"
	@echo "... src/packages/validation/gossip_validation.o"
	@echo "... src/packages/validation/gossip_validation.i"
	@echo "... src/packages/validation/gossip_validation.s"
	@echo "... src/structs/permission/permission.o"
	@echo "... src/structs/permission/permission.i"
	@echo "... src/structs/permission/permission.s"
	@echo "... src/tests/api_protobuf_test.o"
	@echo "... src/tests/api_protobuf_test.i"
	@echo "... src/tests/api_protobuf_test.s"
	@echo "... src/tests/encryption_test.o"
	@echo "... src/tests/encryption_test.i"
	@echo "... src/tests/encryption_test.s"
	@echo "... src/tests/envelope_dispatcher_test.o"
	@echo "... src/tests/envelope_dispatcher_test.i"
	@echo "... src/tests/envelope_dispatcher_test.s"
	@echo "... src/tests/envelope_test.o"
	@echo "... src/tests/envelope_test.i"
	@echo "... src/tests/envelope_test.s"
	@echo "... src/tests/gossip_store_test.o"
	@echo "... src/tests/gossip_store_test.i"
	@echo "... src/tests/gossip_store_test.s"
	@echo "... src/tests/gossip_validation_test.o"
	@echo "... src/tests/gossip_validation_test.i"
	@echo "... src/tests/gossip_validation_test.s"
	@echo "... src/tests/httpclient_test.o"
	@echo "... src/tests/httpclient_test.i"
	@echo "... src/tests/httpclient_test.s"
	@echo "... src/tests/mongoose_test.o"
	@echo "... src/tests/mongoose_test.i"
	@echo "... src/tests/mongoose_test.s"
	@echo "... src/tests/permissions_test.o"
	@echo "... src/tests/permissions_test.i"
	@echo "... src/tests/permissions_test.s"
	@echo "... src/tests/schema_test.o"
	@echo "... src/tests/schema_test.i"
	@echo "... src/tests/schema_test.s"
	@echo "... src/tests/signing_test.o"
	@echo "... src/tests/signing_test.i"
	@echo "... src/tests/signing_test.s"
	@echo "... src/tests/test_init.o"
	@echo "... src/tests/test_init.i"
	@echo "... src/tests/test_init.s"
	@echo "... src/tests/test_runner.o"
	@echo "... src/tests/test_runner.i"
	@echo "... src/tests/test_runner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

